config/routes.rb
Inzomb::Application.routes.draw do

  get "beta/index"

  post "images/new_comment" => "images#new_comment"

  post "beta/validate"

  get "images/index"
  post "images/new" => "images#create"
  get "images/upvote" => "images#upvote"
  get "images/downvote" => "images#downvote"
  get "images/comment_upvote" => "images#comment_upvote"
  get "images/comment_downvote" => "images#comment_downvote"
  get "images/flagPicture" => "images#flagPicture"
  get "images/votes" => "images#votes"
  get "images/recent" => "images#recent"
  get "images/new"
  get "images/delete" => "images#delete"
  get "sessions/new"
  post "users/description" => "users#description"

  get "users/new"
  get "users/liked_photos/:username" => "users#liked_photos"
  get "users/uploaded_photos/:username" => "users#uploaded_photos"

  get "upload" => "images#new", :as => "upload"

  get "images" => "images#index", :as => "images"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root :to => "images#index"
  resources :users
  resources :sessions
  resources :images

  resources :beta

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :votes, :foreign_key => :image_id
  has_many :comments, :foreign_key => :image_id

  accepts_nested_attributes_for :comments
  validates_attachment_presence :image
  validates_attachment_size :image, :in => 1..3000000
  validates_attachment_content_type :image,  :content_type => ['image/jpeg', 'image/png']

  paginates_per 60

  has_attached_file :image,
    :styles => { :thumb => "100x100#", :thumb2 => "200x200#", :large => "1000x2000>"},
    :storage => :s3,
      :s3_credentials => S3_CREDENTIALS,
      :path => ":attachment/:id/:style.:extension",
      :url => ":s3_alias_url",
      :s3_host_alias => 'img.inzomb.com'

  def vote_exists(user)
    upvote_exists(user) || downvote_exists
  end
  def upvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => true)
  end

  def downvote_exists(user)
    return false if user.nil?
    self.votes.exists?(:user_id => user.id, :upvote => false)
  end

  def upvote
    self.upscore += 1
    self.save
  end
  def downvote
    self.downscore -= 1
    self.save
  end
  def score
    self.upscore
  end
  def self.ten_most_recent
    return order("created_at desc").limit(10)
  end
  def self.ten_most_votes
    return order("upscore desc").limit(10)
  end
  def recent_comments
    return self.comments.order("created_at desc").limit(5)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate, :except => [:index, :votes, :recent]

  def index
    recent
  end
  def recent
    @images = Image.order("created_at DESC").page(params[:page])
    if current_user.nil?
      @logged = false
    end
    @category = :recent
    render :index
  end
  def new_comment
    @comment = Comment.new(params[:comment])
    @comment.save!
    @image = Image.find(@comment.image_id)
    respond_to do |format|
      format.html {redirect_to :action => :index, :notice => "Comment successful"}
      format.js 
    end
  end
  def votes
    @comment = Comment.new
    @category = :votes
    @images = Image.order("upscore + downscore DESC").page(params[:page])
    render :index
  end
  def upvote
    @image = Image.find_by_id(params[:id])
    @image.upvote
    Vote.create!( :user => current_user, :image => @image, :upvote => true)
    @image.reload
    respond_to do |format|  
      format.html { redirect_to images_path }  
      format.js
    end     
  end
  def comment_upvote
    comment = Comment.find_by_id(params[:id])
    @image = Image.find(comment.image_id)
    comment.upvote
    Vote.create!( :user => current_user, :comment => comment, :upvote => true)
    respond_to do |format|
      format.html {redirect_to images_path}
      format.js
    end
  end
  def comment_downvote
    comment = Comment.find_by_id(params[:id])
    @image = Image.find(comment.image_id)
    comment.downvote
    Vote.create!( :user => current_user, :comment => comment, :upvote => false)
    respond_to do |format|
      format.html {redirect_to images_path}
      format.js
    end
  end
  def flagPicture
    image = Image.find_by_id(params[:id])
    UserMailer.flagPicture(image, current_user).deliver
    redirect_to images_path
  end
  def downvote
    @image = Image.find_by_id(params[:id])
    @image.downvote
    Vote.create!( :user => current_user, :image => @image, :upvote => false)
    @image.reload
    respond_to do |format|
      format.html {redirect_to images_path}
      format.js
    end
  end
  def create
    @image = Image.new(params[:image])
    @image.user_id = current_user.id
    @image.upscore = 0
    @image.downscore = 0
    if @image.save
      redirect_to :action => :index, :notice => "Image Successfully Uploaded"
    else
      render "new"
    end

  end
    def delete_comment
    comment = Comment.find_by_id(params[:id])
    comment.comment_text = '[deleted]'
    if comment.save
      redirect_to :action => :index, :notice => "Comment successfully deleted"
    end
  end
  def delete
    image = Image.find_by_id(params[:id])
    if image.delete
      redirect_to :action => :index, :notice => "Image successfully deleted"
    end
  end
  def new
    @image = Image.new
  end

protected
  def authenticate
    if !current_user
      redirect_to :controller => :sessions, :action => :new, :notice => "Please login before uploading image"
    end
  end
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/image/index.html.erb
<div id="categories">
  <%= link_to "Upload Image", upload_path %> - 
	<%= link_to_unless_current "Most Recent", images_path %> -
	<%= link_to_unless_current "Top Votes", :controller => :image, :action => :votes %>
  
</div>
<% @images.each do |image| %>
    <div id='image_post'>
      <div id='voting_layout' class="halign">
          <% if image.upvote_exists(current_user) %>
              <%= image_tag("up_voted.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= image_tag("down_arrow.png") %>
          <% elsif image.downvote_exists(current_user) %>
                <%= image_tag("up_arrow.png") %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= image_tag("down_voted.png") %>
          <% else %>
                <%= link_to image_tag("up_arrow.png", :mouseover => "up_voted.png"), {:action => :upvote, :id => image.id} %>
                <br>  &nbsp;  <font size="5"> <%= image.upscore + image.downscore %> </font>  <br>
                <%= link_to image_tag("down_arrow.png", :mouseover => "down_voted.png"), {:action => :downvote, :id => image.id} %>
          <% end %>
         </div>
      </div>
      <div id='image_post' class="halign">

	<span id='image_top'>
		<span id='image_username'>
			<%= profile_link(image.user) %>
		</span>
		<span id='image_caption'>
			<%= image.caption %>
		</span>
	</span>
	<div id='image_square' class='image_resizer'>
    <div style="display:block">
		<%= link_to(image_tag(image.image.url(:large)), image.image.url ) unless image.image.nil? %>
    </div>
      <span id='image_time'>
      		Posted <%= time_ago_in_words(image.created_at) %> ago.
            <% if(image.user == current_user) %>
            <%=   link_to '[delete image]', {:action => :delete, :id => image.id, :confirm => 'Are you sure you want to delete this image?'} %>
            <% end %>
            <%=  link_to " [report]",{:action => :flagPicture, :id => image.id}  %> 
      	</span>
	</div>
    <div id="comments">
      <% if !current_user.nil? %>
      <div id='new_comment'>
        <%=  form_for @comment, :url => {:action => :new_comment} do |f| %>
            <%= f.text_field :comment_text %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :image_id, :value => image.id %>
            <%= f.submit "Comment" %>
        <% end %>

      </div>
       <% end %>
        <%  image.recent_comments.each do |comment| %>
        <div id='comment'>
			<div id='comment_vote'>
				<% if comment.upvote_exists(current_user) %>
		               <%= Vote.comment_score(comment.id) %>
						<div>
						<%= image_tag("up_voted.png", :size => "15x15") %><br><%= image_tag("down_arrow.png", :size => "14x14") %>
						</div>
		          <% elsif comment.downvote_exists(current_user) %>
		                <%= Vote.comment_score(comment.id) %>
						<div>
						<%= image_tag("up_arrow.png", :size => "15x15") %><br><%= image_tag("down_voted.png", :size => "15x15") %>
						</div>
		          <% else  %>
		                <%= Vote.comment_score(comment.id) %>
						<div>
						 <%= link_to image_tag("up_arrow.png", :mouseover => "up_voted.png", :size => "15x15"), {:action => :comment_upvote, :id => comment.id} %><br><%= link_to image_tag("down_arrow.png", :mouseover => "down_voted.png", :size => "15x15"), {:action => :comment_downvote, :id => comment.id} %>
						</div>
		          <% end %>
			</div>
            <div id='comment_top'><span id='comment_username'><%=   profile_link(comment.user) %></span><span id='comment_time'><%=  time_ago_in_words(comment.created_at) %>            
            <% if(comment.user == current_user) %>
            <%=   link_to '[delete comment]', {:action => :delete_comment, :id => comment.id} %>
            <% end %>
            </div>
            </span>

            <div id='comment_text'><%=  comment.comment_text %></div>
        </div>
        <% end %>
    </div>
</div>
<br>
<% end %>