config/routes.rb
Inzomb::Application.routes.draw do

  get "beta/index"

  post "images/new_comment" => "images#new_comment"

  post "beta/validate"

  get "images/index"
  post "images/new" => "images#create"
  get "images/upvote" => "images#upvote"
  get "images/downvote" => "images#downvote"
  get "images/comment_upvote" => "images#comment_upvote"
  get "images/comment_downvote" => "images#comment_downvote"
  get "images/flagPicture" => "images#flagPicture"
  get "images/votes" => "images#votes"
  get "images/recent" => "images#recent"
  get "images/new"
  get "images/delete" => "images#delete"
  get "sessions/new"
  post "users/description" => "users#description"

  get "users/new"
  get "users/liked_photos/:username" => "users#liked_photos"
  get "users/uploaded_photos/:username" => "users#uploaded_photos"

  get "upload" => "images#new", :as => "upload"

  get "images" => "images#index", :as => "images"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root :to => "images#index"
  resources :users
  resources :sessions
  resources :images

  resources :beta

end

app/views/shared/_navbar.html.erb
<div id="navbar_right">

  		<% if current_user %>
    		<span id='image_username'><%= profile_link(current_user) %></span> -
    		<%= link_to "Logout", logout_path %> -
  		<% else %>
    		<%= link_to "Signup", signup_path %> -
    		<%= link_to "Login", login_path %>
  		<% end %>

</div>